services:
  db:
    image: mysql:9
    container_name: chronos_db
    restart: always
    shm_size: 128mb
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PWD}
      MYSQL_DATABASE: chronos
    volumes:
      # Datenbank-Volume für persistente MySQL-Daten
      - chronos-database:/var/lib/mysql
      # Init-SQL für Podman rootless, SELinux-kompatibel
      - ./init-sql:/docker-entrypoint-initdb.d:Z
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  mock-smtp:
    image: haravich/fake-smtp-server
    container_name: mock-smtp
    ports:
      - "1025:1025"
      - "1080:1080"

volumes:
  chronos-database: