services:
  db:
    image: mysql:9
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PWD}
      MYSQL_DATABASE: chronos
    volumes:
      - chronos-database:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  mock-smtp:
    image: haravich/fake-smtp-server
    container_name: mock-smtp
    ports:
      - "1025:1025"
      - "1080:1080"

volumes:
  chronos-database: