services:
  frontend:
    image: ghcr.io/silverminer007/chronos-frontend:dev-master
    ports:
      - "8080:8080"
      - "5005:5005"
      - "35729:35729"
    env_file: .env
    environment:
      JAVA_TOOL_OPTIONS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
    depends_on:
      db:
        condition: service_healthy
    networks:
      frontend:
      messaging:
    volumes:
      - ./logs/:/logs/

  cron:
    image: ghcr.io/silverminer007/chronos-cron:dev-master
    depends_on:
      db:
        condition: service_healthy
    env_file: .env
    ports:
      - "5006:5005"
    environment:
      JAVA_TOOL_OPTIONS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
    networks:
      backend:
      messaging:
    volumes:
      - ./logs/:/logs/

  db:
    image: mysql
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PWD}
      MYSQL_DATABASE: chronos
    volumes:
      - chronos-database:/var/lib/mysql
    networks:
      frontend:
      backend:
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  email:
    image: ghcr.io/silverminer007/email:dev-master
    container_name: email
    env_file: .env
    ports:
      - "5007:5005"
    environment:
      JAVA_TOOL_OPTIONS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
    networks:
      messaging:
    volumes:
      - ./logs/:/logs/

  mock-smtp:
    image: haravich/fake-smtp-server
    container_name: mock-smtp
    ports:
      - "1025:1025"
      - "1080:1080"
    networks:
      messaging:

  signal:
    image: bbernhard/signal-cli-rest-api:latest
    container_name: signal
    ports:
      - "8095:8080"
    environment:
      MODE: json-rpc
    volumes:
      - signal:/home/.local/share/signal-cli

volumes:
  chronos-database:
  signal:

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
  messaging:
    driver: bridge
