run-name: Deploy by @${{ github.actor }}

on:
  push:

permissions:
  packages: write
  contents: read
  attestations: write
  id-token: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.actor }}

jobs:
  build:
    name: Build sources
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up JDK 21 for x64
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Test
        run: mvn --batch-mode --update-snapshots verify

      - if: ${{ startsWith(github.ref, 'refs/tags/') }}
        name: Create and push docker images for tags
        run: mvn package jib:build -Pproduction -Dchronos.version=${{ github.event.release.tag_name }}

      - if: ${{ ! startsWith(github.ref, 'refs/tags/') }}
        name: Create and push docker images for push
        run: mvn package jib:build -Pproduction
